name: Code style
concurrency:
  group: on_push
  cancel-in-progress: true

on:
  push: {}
  workflow_dispatch: {}

jobs:
  unit-tests:
    name: Code style
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        include:
          - version: "3.11"
            check-formatting: "true"
            check-consistency: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install the project
        run: |
          uv sync --all-extras --dev
          uv pip install mypy pre-commit
      - name: Run pre-commit
        run: uv run pre-commit run --all-files
      - name: Stubs consistency check
        if: ${{ matrix.check-consistency }}
        run: |
          uv pip install -e . --config-settings editable_mode=compat
          uv run istub -d
